### ISSUE TITLE
Fade-out animation disappears crude rather than fades away.

### ISSUE THREAD

**Issue by apoapostolov** [Handyfon/heartbeat#1]
Tested in Electron and in Chrome. For some reason the overlay disappears with a very hard abrupt effect instead of a fade-out.

Example: https://streamable.com/ubiejl

**Comment by Handyfon** [comment]
This is indeed interesting. I cannot replicate this problem with my test worlds, perhaps this is a problem between modules?

**Comment by apoapostolov** [comment]
Hello, sorry that I lapsed on this issue. I identified a conflict with SmallTime time widget. When it is on, Heartbeat animation locks and hard-disappears when fading out.

**Comment by Handyfon** [comment]
finally fixed in 10.2.1, thank you again for bringing this to my attention
