### ISSUE TITLE
V11 Error

### ISSUE THREAD

**Issue by uniwars** [Handyfon/heartbeat#11]
Hi, after updating to v11 I get this error in the module setup page : 

The module "heartbeat" is using "name" which is deprecated in favor of "id"
The module "heartbeat" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by gandb** [comment]
The same here, but only the old flat issue.

**Comment by Jorseggil** [comment]
Same issuea as gandb
