### ISSUE TITLE
[BUG] You can see the top part of the image used for the "blood" animation

### ISSUE THREAD

**Issue by TrofimSelbs** [Handyfon/heartbeat#14]
Hey, thank you for this wonderful module! My players have noticed a small UI issue with the top part of the blood animations. Basically, it jumps down and up and you can see its border clearly

https://github.com/user-attachments/assets/9b5fb3e5-db14-4323-9ed9-cec8b4ff4f2a

**Comment by Handyfon** [comment]
Thanks for reporting this, fixed in the next version

**Comment by TrofimSelbs** [comment]
Hey, thank you for fixing it! I seem to have accidentally deleted the module and I can't seem to find it in Foundry. Is Heartbeat v12 compatible?
