### ISSUE TITLE
SWADE - System Request

### ISSUE THREAD

**Issue by brunocalado** [Handyfon/heartbeat#2]
Hi. Great module.

Can you make it work well for SWADE?

SWADE work with the reverse "HP". 0 means healthy, 3 means dying. 

![image](https://user-images.githubusercontent.com/4999783/214688354-509538fb-d2ea-4e17-bc71-87cd1a946e19.png)

**Comment by StealthRevealed** [comment]
I came here to say the same thing! If we could reverse HP definition that would be awesome. :)

**Comment by Handyfon** [comment]
Systems that use wounds are now supported!
