### ISSUE TITLE
[BUG] Error When Token Has No Actor

### ISSUE THREAD

**Issue by Larkinabout** [Handyfon/heartbeat#4]
![image](https://user-images.githubusercontent.com/105953297/231120021-4817bb0a-e532-45dc-aafb-48af37db3bba.png)

The error occurs at this line:
![image](https://user-images.githubusercontent.com/105953297/231120547-b5bf877e-2b7e-48ba-a2da-7c9b570e6c24.png)
When called here:
![image](https://user-images.githubusercontent.com/105953297/231121070-e9b9771b-283c-40b0-9a40-d2d4f3440765.png)

**Comment by Handyfon** [comment]
fixed
