### ISSUE TITLE
Issue with 10.2.3

### ISSUE THREAD

**Issue by apoapostolov** [Handyfon/heartbeat#7]
Great new update fixing almost all issues from previous version. Some PF2 minor issues remain:

1. The Heart On/Off icon in the upper right corner overlaps with the Effects Panel in PF2. Why not add Toolbar Icon to turn on/off like some other mods do like Splatter? Or quick setting option to turn off. 
2. Colors for damage are reversed in PF2. Damage is green, Healing is red.
3. Heartbeat HP% doesn't seem to respect increase of the threshold, changed it to 20% but would still trigger only at 10%. 
4. I couldn't get the Massive Damage sound to play at all
5. The constant blue toasts for change of brightness are annoying, perhaps this is a debug left from development versions? If not, option to turn off would be nice. 
![image](https://github.com/Handyfon/heartbeat/assets/4083812/66dd4d05-b695-46a5-a1a2-a6718dde0f84)

**Comment by Llethander** [comment]
Issues 1, 3, and 5 are not specific to PF2 as I noticed the same for D&D 5e. Additionally, the brightness toast pops up even if the brightness option is disabled.

**Comment by Handyfon** [comment]
1 - Added options where it should be displayed. Alternatives will be considered for the next versions.
2 - This is because of the way pf2e calculates damage. There is a option in the settings to invert the colors for systems like pf2e.
3, 4 and 5 are fixed in 10.2.4

**Comment by apoapostolov** [comment]
Thank you very much
